### ISSUE TITLE
Исправить импорты (особенно Excel)

### ISSUE THREAD

**Issue by Yaspeace** [Yaspeace/FileToSqlConverter#1]
* Перенести строку с файлом в окна импорта
* Добавить в импорт екселя возможность вручную ввести диапазон столбцов и строк
* На основном окне сделать вывод информации о текущем импортированном файле
* ~~Добавить FileAdapter-заглушку, которая будет пока файл не импортирован~~ - готово (отдельно)

**Comment by podisodi** [comment]
Выбор диапазона импорта для ексель вынесу в отдельную задачу
